- name: install kubeadm and friends
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker
    - kubeadm
    - kubectl
    - kubelet

- name: make sure kubelet and docker are running
  service:
    name: "{{ item }}"
    state: running
    enabled: yes
  with_items:
    - kubelet
    - docker

- name: kubeadm token file
  copy:
    content: abcdef.1234567890abcdef
    dest: /root/kubeadm-token
