- name: install flannel
  dnf:
    name: flannel
    state: present

- name: flannel service options
  template:
    src: flanneld.j2
    dest: /etc/sysconfig/flanneld

- name: flannel config in etcd
  include: etcd_config.yml
  when: flannel_etcd_config

- name: start flannel
  service:
    name: flanneld
    state: running
    enabled: true
