- hosts: masters nodes
  roles:
    - kube_hosts

- hosts: masters
  roles:
    - kube_master_prereq
    - kube_common
    - etcd
    - kube_master

- hosts: nodes
  roles:
    - kube_node_prereq
    - kube_common
